name: "Hello Actions"
description: "Greet Someone"
author: "actocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "WORLD"
  
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
